# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\temp\py\GUI\autotest_ecutest4.5\NewCreate.ui'
#
# Created: Wed Feb 20 14:34:05 2019
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewCreateDlg(object):
    def setupUi(self, NewCreateDlg):
        NewCreateDlg.setObjectName(_fromUtf8("NewCreateDlg"))
        NewCreateDlg.resize(808, 314)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        NewCreateDlg.setFont(font)
        NewCreateDlg.setLayoutDirection(QtCore.Qt.LeftToRight)
        NewCreateDlg.setStyleSheet(_fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(NewCreateDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 36, 761, 141))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditcase = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditcase.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.lineEditcase.setFont(font)
        self.lineEditcase.setObjectName(_fromUtf8("lineEditcase"))
        self.gridLayout.addWidget(self.lineEditcase, 0, 1, 1, 1)
        self.pushButtoncase = QtGui.QPushButton(self.layoutWidget)
        self.pushButtoncase.setObjectName(_fromUtf8("pushButtoncase"))
        self.gridLayout.addWidget(self.pushButtoncase, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEditusermap = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditusermap.setObjectName(_fromUtf8("lineEditusermap"))
        self.gridLayout.addWidget(self.lineEditusermap, 2, 1, 1, 1)
        self.pushButtonusermap = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonusermap.setObjectName(_fromUtf8("pushButtonusermap"))
        self.gridLayout.addWidget(self.pushButtonusermap, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEditmodelmap = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditmodelmap.setObjectName(_fromUtf8("lineEditmodelmap"))
        self.gridLayout.addWidget(self.lineEditmodelmap, 3, 1, 1, 1)
        self.pushButtonmodelmap = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonmodelmap.setObjectName(_fromUtf8("pushButtonmodelmap"))
        self.gridLayout.addWidget(self.pushButtonmodelmap, 3, 2, 1, 1)
        self.lineEdita2l = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdita2l.setObjectName(_fromUtf8("lineEdita2l"))
        self.gridLayout.addWidget(self.lineEdita2l, 1, 1, 1, 1)
        self.pushButtona2l = QtGui.QPushButton(self.layoutWidget)
        self.pushButtona2l.setObjectName(_fromUtf8("pushButtona2l"))
        self.gridLayout.addWidget(self.pushButtona2l, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(NewCreateDlg)
        self.layoutWidget1.setGeometry(QtCore.QRect(570, 250, 221, 51))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonOK = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setObjectName(_fromUtf8("pushButtonOK"))
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.pushButtonclose = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButtonclose.setFont(font)
        self.pushButtonclose.setObjectName(_fromUtf8("pushButtonclose"))
        self.horizontalLayout.addWidget(self.pushButtonclose)
        self.layoutWidget2 = QtGui.QWidget(NewCreateDlg)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 190, 272, 32))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.comboBoxHIL = QtGui.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.comboBoxHIL.setFont(font)
        self.comboBoxHIL.setStyleSheet(_fromUtf8(""))
        self.comboBoxHIL.setObjectName(_fromUtf8("comboBoxHIL"))
        self.comboBoxHIL.addItem(_fromUtf8(""))
        self.comboBoxHIL.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxHIL)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label.setBuddy(self.lineEditcase)
        self.label_4.setBuddy(self.lineEditusermap)
        self.label_5.setBuddy(self.lineEditmodelmap)
        self.label_6.setBuddy(self.lineEditusermap)
        self.label_2.setBuddy(self.comboBoxHIL)

        self.retranslateUi(NewCreateDlg)
        QtCore.QObject.connect(self.pushButtonclose, QtCore.SIGNAL(_fromUtf8("clicked()")), NewCreateDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(NewCreateDlg)
        NewCreateDlg.setTabOrder(self.lineEditcase, self.pushButtoncase)
        NewCreateDlg.setTabOrder(self.pushButtoncase, self.lineEditusermap)
        NewCreateDlg.setTabOrder(self.lineEditusermap, self.pushButtonusermap)
        NewCreateDlg.setTabOrder(self.pushButtonusermap, self.lineEditmodelmap)
        NewCreateDlg.setTabOrder(self.lineEditmodelmap, self.pushButtonmodelmap)
        NewCreateDlg.setTabOrder(self.pushButtonmodelmap, self.pushButtonOK)
        NewCreateDlg.setTabOrder(self.pushButtonOK, self.pushButtonclose)

    def retranslateUi(self, NewCreateDlg):
        NewCreateDlg.setWindowTitle(_translate("NewCreateDlg", "TestCase Create Select", None))
        self.label.setText(_translate("NewCreateDlg", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">TestcasePath:</span></p></body></html>", None))
        self.pushButtoncase.setText(_translate("NewCreateDlg", "SetPath", None))
        self.label_4.setText(_translate("NewCreateDlg", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">UsermapPath:</span></p></body></html>", None))
        self.pushButtonusermap.setText(_translate("NewCreateDlg", "SetPath", None))
        self.label_5.setText(_translate("NewCreateDlg", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">ModelmapPath:</span></p></body></html>", None))
        self.pushButtonmodelmap.setText(_translate("NewCreateDlg", "SetPath", None))
        self.pushButtona2l.setText(_translate("NewCreateDlg", "SetPath", None))
        self.label_6.setText(_translate("NewCreateDlg", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">      A2LPath:</span></p></body></html>", None))
        self.pushButtonOK.setText(_translate("NewCreateDlg", "OK", None))
        self.pushButtonclose.setText(_translate("NewCreateDlg", "close", None))
        self.comboBoxHIL.setItemText(0, _translate("NewCreateDlg", "DSPACE", None))
        self.comboBoxHIL.setItemText(1, _translate("NewCreateDlg", "  ETAS", None))
        self.label_2.setText(_translate("NewCreateDlg", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Select HIL Type:</span></p></body></html>", None))

